export const WHO_AM_I_REQUEST = 'WHO_AM_I_REQUEST'
export const WHO_AM_I_SUCCESS = 'WHO_AM_I_SUCCESS'
export const WHO_AM_I_FAILURE = 'WHO_AM_I_FAILURE'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const GET_NUMBERS_REQUEST = 'GET_NUMBERS_REQUEST'
export const GET_NUMBERS_SUCCESS = 'GET_NUMBERS_SUCCESS'
export const GET_NUMBERS_FAILURE = 'GET_NUMBERS_FAILURE'

export const ADD_NUMBER_REQUEST = 'ADD_NUMBER_REQUEST'
export const ADD_NUMBER_SUCCESS = 'ADD_NUMBER_SUCCESS'
export const ADD_NUMBER_FAILURE = 'ADD_NUMBER_FAILURE'

export const CHANGE_PRIORITY_REQUEST = 'CHANGE_PRIORITY_REQUEST'
export const CHANGE_PRIORITY_SUCCESS = 'CHANGE_PRIORITY_SUCCESS'
export const CHANGE_PRIORITY_FAILURE = 'CHANGE_PRIORITY_FAILURE'

export const GET_ALL_MESSAGES_REQUEST = 'GET_ALL_MESSAGES_REQUEST'
export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS'
export const GET_ALL_MESSAGES_FAILURE = 'GET_ALL_MESSAGES_FAILURE'

export const ADD_MESSAGE_REQUEST = 'ADD_MESSAGE_REQUEST'
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE'

export const GET_ALL_RULES_REQUEST = 'GET_ALL_RULES_REQUEST'
export const GET_ALL_RULES_SUCCESS = 'GET_ALL_RULES_SUCCESS'
export const GET_ALL_RULES_FAILURE = 'GET_ALL_RULES_FAILURE'

export const ADD_RULE_REQUEST = 'ADD_RULE_REQUEST'
export const ADD_RULE_SUCCESS = 'ADD_RULE_SUCCESS'
export const ADD_RULE_FAILURE = 'ADD_RULE_FAILURE'
